name: "Run"

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]

jobs:
  analyze:
    name: "01 - Run Analyzer"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run basic test
        run: |
          ./loganalyzer.py --url=https://obsproject.com/logs/tGzdILvSRDMSpulg
  ubuntu64:
    name: "02 - Code Format Check"
    runs-on: ubuntu-latest
    if: always()
    needs: [analyze]
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pycodestyle
        run: |
          ./check_pep8.sh
