name: "Run"

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]

jobs:
  analyze:
    name: "01 - Run Analyzer"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run basic test
        run: |
          ./loganalyzer.py --url=https://obsproject.com/analyzer/test_logfile.txt
  ubuntu64:
    name: "02 - Code Format Check"
    runs-on: ubuntu-22.04
    if: always()
    needs: [analyze]
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Annotate linting errors
        uses: marian-code/python-lint-annotate@ffe24b32a33241b668ab6d34150d7d8e1ad744ec
        with:
          python-root-list: "."
          use-black: false
          use-isort: false
          use-mypy: false
          use-pycodestyle: true
          use-pydocstyle: false
          use-pylint: false
          use-flake8: false
          use-vulture: false
          extra-pycodestyle-options: "--config=setup.cfg"
          python-version: "3.8"
      - name: Run pycodestyle
        # This is required because the annotate action doesn't trigger a failure
        run: |
          ./check_pep8.sh 1> /dev/null
